---
title: "期中專案Olist電商分析"
author: "第12組"
date: "`r Sys.time()`"
output: 

  html_document:

    toc: true

    toc_depth: 2

    toc_float:

      collapsed: false

      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
chooseCRANmirror(graphics=FALSE, ind=1)
if(!require(pacman)) install.packages("pacman")
pacman::p_load(dplyr)
if (!require('ggplot2')) 
{
  install.packages('ggplot2');
  library(ggplot2);
}
if (!require('maps')) 
{
  install.packages('maps');
  library(maps);
}
if (!require('mapdata')) 
{
  install.packages('mapdata');
  library(mapdata);
}
if (!require('maptools')) 
{
  install.packages('maptools');
  library(maptools);
}
if (!require('plyr')) 
{
  install.packages('plyr');
  library(plyr);
}

if (!require('tidyverse')) 
{
  install.packages('tidyverse');
  library(tidyverse);
}
if (!require('plotly')) 
{
  install.packages('plotly');
  library(plotly);
}
if (!require('gapminder')) 
{
  install.packages('gapminder');
  library(gapminder);
}
if (!require('FactoMineR')) 
{
  install.packages('FactoMineR');
  library(FactoMineR);
} 
if (!require('d3heatmap')) 
{
  install.packages('d3heatmap');
  library(d3heatmap);
} 

pacman::p_load(factoextra)
```

```{r}
library(readr)
All_Data <- read_csv("All Data.csv")
olist<- read_csv("All Data.csv")
All_Data$actual_pay=(All_Data$payment_value - All_Data$freight_value)
All_Data$quantity=(All_Data$actual_pay/All_Data$price) %>% round()
All_Data$reviewdate=format(as.Date(All_Data$review_answer_timestamp),"%Y/%m")
All_Data$Year=format(as.Date(All_Data$review_answer_timestamp),"%Y")
```


##綜觀三年交易量與利潤
```{r}
totalsell=aggregate(All_Data$quantity,list(All_Data$Year),sum,na.rm=T)
colnames(totalsell)=c("Year","Quantity")
totalpay=aggregate(All_Data$actual_pay,list(All_Data$Year),sum,na.rm=T)
colnames(totalpay)=c("Year","Payment")

ggplot(totalsell,aes(x=Year,y=Quantity))+
  geom_histogram(stat="identity",fill="green")+
  geom_line(data= totalpay,aes(x=Year,y=Payment,group=1,color="totalpay"))+
  scale_y_log10()+
  scale_colour_manual(name = "Line",values="blue")
```


##全巴西交易量，取交易最多的五州
```{r}
five_city<-filter(olist,customer_state %in% c("SP","PR","RJ","RS","MG"))
five_city$actuall_pay=five_city$payment_value-five_city$freight_value
five_city$quantity=(five_city$actuall_pay/five_city$price) %>% round()
```

##篩選五大洲的五大熱門產品
```{r}
top10_in_SP<-table(five_city$product_category_name_english) %>% sort %>%
tail(5) %>% names()
top10_in_SPf<-filter(five_city,product_category_name_english %in% top10_in_SP)
top10_in_SP
```
##五大熱門產品在五大洲的銷售量
```{r}
  ggplot()+
  geom_bar(data=top10_in_SPf,aes(customer_state,fill=product_category_name_english),width=0.8,position = "dodge",alpha=0.6)+
  scale_y_log10()
```

##主成分分析
```{r}
top10_in_SPf<-filter(top10_in_SPf,is.na(top10_in_SPf$price)==FALSE)
g<-split(top10_in_SPf,top10_in_SPf$customer_state)


SP<-tapply(g$SP$quantity, g$SP$product_category_name_english, sum,na.rm=T)
PR<-tapply(g$PR$quantity, g$PR$product_category_name_english, sum,na.rm=T)
RJ<-tapply(g$RJ$quantity, g$RJ$product_category_name_english, sum,na.rm=T)
MG<-tapply(g$MG$quantity, g$MG$product_category_name_english, sum,na.rm=T)
RS<-tapply(g$RS$quantity, g$RS$product_category_name_english, sum,na.rm=T)
FIVE<-rbind(SP,PR,RJ,RS,MG)
fpca<-as.data.frame(FIVE)
fpca1<-select(fpca,top10_in_SP)
```

```{r}
pca = PCA(fpca1[,1:5])

get_eigenvalue(pca)

pca$ind$cos2
```


```{r}
fviz_pca_biplot(
  pca, pointsize="cos2", repel=T,
  col.var="red", col.ind="#E7B800", alpha.ind=0.3)
```

#最常購買時間
```{r}
o=as.POSIXct(as.character(five_city$order_purchase_timestamp,format="%Y-%m-%d %H:%M"))
month = format(o,"%m")
weekday = format(o,"%u")
hour = format(o,"%H")
```

```{r}
Sys.setlocale("LC_ALL", "en_US")
qplot(month,data=five_city,geom="bar",fill=weekday)
```

```{r fig.height=3.2, fig.width=6.4}
table(format(o,"%H"),format(o,"%u")) %>% t %>%
  as.data.frame.matrix %>% 
  d3heatmap(F,F,col=colorRamp(c("#00bfff","#ffffe6","#ff6666")))
```

#支付方式
```{r}
ggplot(five_city,aes(x=customer_state,fill=payment_type))+
  geom_bar(position = "stack")
```


#五州的評價走勢圖

```{r}
SP=filter(All_Data,customer_state=="SP")
SPmonthly_score=aggregate(SP$review_score,list(SP$reviewdate),mean,na.rm=T)
colnames(SPmonthly_score)=c("Month","Score")
RJ=filter(All_Data,customer_state=="RJ")
RJmonthly_score=aggregate(RJ$review_score,list(RJ$reviewdate),mean,na.rm=T)
colnames(RJmonthly_score)=c("Month","Score")
MG=filter(All_Data,customer_state=="MG")
MGmonthly_score=aggregate(MG$review_score,list(MG$reviewdate),mean,na.rm=T)
colnames(MGmonthly_score)=c("Month","Score")
RS=filter(All_Data,customer_state=="RS")
RSmonthly_score=aggregate(RS$review_score,list(RS$reviewdate),mean,na.rm=T)
colnames(RSmonthly_score)=c("Month","Score")
PR=filter(All_Data,customer_state=="PR")
PRmonthly_score=aggregate(PR$review_score,list(PR$reviewdate),mean,na.rm=T)
colnames(PRmonthly_score)=c("Month","Score")

ggplot(SPmonthly_score,aes(x=Month,y=Score,group=1,color="SP"))+
  geom_line()+
  geom_line(data=RJmonthly_score,aes(x=Month,y=Score,group=2,color="RJ"))+
  geom_line(data=MGmonthly_score,aes(x=Month,y=Score,group=3,color="MG"))+
  geom_line(data=RSmonthly_score,aes(x=Month,y=Score,group=4,color="RS"))+
  geom_line(data=PRmonthly_score,aes(x=Month,y=Score,group=5,color="PR"))+
  theme(axis.text.x=element_text(angle = 90, colour = "black"))+
  scale_colour_manual(name = "State",
                      values=c("red","blue","black","green","purple"))
```